// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SystemInfo {
    "hostname": string;
    "os": string;
    "arch": string;
    "numCPU": number;

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("numCPU" in $$source)) {
            this["numCPU"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}
