// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetArch(): $CancellablePromise<string> {
    return $Call.ByID(2622494641);
}

export function GetHostname(): $CancellablePromise<string> {
    return $Call.ByID(3309448004);
}

export function GetNumCPU(): $CancellablePromise<number> {
    return $Call.ByID(2830413863);
}

export function GetOS(): $CancellablePromise<string> {
    return $Call.ByID(3999062015);
}

export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(3288884904).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SystemInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
